using './main.bicep'

param environmentName = readEnvironmentVariable('AZURE_ENV_NAME', 'dev')
param location = readEnvironmentVariable('AZURE_LOCATION', 'swedencentral')
param principalId = readEnvironmentVariable('AZURE_PRINCIPAL_ID')
param foundryResourceName = readEnvironmentVariable('AZURE_FOUNDRY_RESOURCE_NAME', '')
param realtimeDeploymentName = readEnvironmentVariable('AZURE_OPENAI_REALTIME_DEPLOYMENT', 'gpt-realtime-1.5')
param realtimeModelVersion = readEnvironmentVariable('AZURE_OPENAI_REALTIME_MODEL_VERSION', '2026-02-23')
param embeddingDeploymentName = readEnvironmentVariable('AZURE_OPENAI_EMBEDDING_DEPLOYMENT', 'text-embedding-3-large')
param embeddingModelVersion = readEnvironmentVariable('AZURE_OPENAI_EMBEDDING_MODEL_VERSION', '1')
param transcriptionDeploymentName = readEnvironmentVariable('AZURE_OPENAI_TRANSCRIPTION_DEPLOYMENT', 'gpt-4o-mini-transcribe')
param transcriptionModelVersion = readEnvironmentVariable('AZURE_OPENAI_TRANSCRIPTION_MODEL_VERSION', '2025-12-15')
param searchSku = readEnvironmentVariable('AZURE_SEARCH_SKU', 'serverless')
param entraClientId = readEnvironmentVariable('ENTRA_CLIENT_ID', '')
param entraClientSecret = readEnvironmentVariable('ENTRA_CLIENT_SECRET', '')
